# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from crazyflie/PlanGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import crazyflie.msg

class PlanGoal(genpy.Message):
  _md5sum = "10456e964d2e5406cf0e6a1df9aa5bd6"
  _type = "crazyflie/PlanGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
float64[] interval_list
crazyflie/Command[] command_list

================================================================================
MSG: crazyflie/Command
float64 accel
float64 roll
float64 pitch
float64 yaw"""
  __slots__ = ['interval_list','command_list']
  _slot_types = ['float64[]','crazyflie/Command[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       interval_list,command_list

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PlanGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.interval_list is None:
        self.interval_list = []
      if self.command_list is None:
        self.command_list = []
    else:
      self.interval_list = []
      self.command_list = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.interval_list)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.interval_list))
      length = len(self.command_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.command_list:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.accel, _x.roll, _x.pitch, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.command_list is None:
        self.command_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.interval_list = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command_list = []
      for i in range(0, length):
        val1 = crazyflie.msg.Command()
        _x = val1
        start = end
        end += 32
        (_x.accel, _x.roll, _x.pitch, _x.yaw,) = _get_struct_4d().unpack(str[start:end])
        self.command_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.interval_list)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.interval_list.tostring())
      length = len(self.command_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.command_list:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.accel, _x.roll, _x.pitch, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.command_list is None:
        self.command_list = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.interval_list = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.command_list = []
      for i in range(0, length):
        val1 = crazyflie.msg.Command()
        _x = val1
        start = end
        end += 32
        (_x.accel, _x.roll, _x.pitch, _x.yaw,) = _get_struct_4d().unpack(str[start:end])
        self.command_list.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
