// Generated by gencpp from file crazyflie/Plan.msg
// DO NOT EDIT!


#ifndef CRAZYFLIE_MESSAGE_PLAN_H
#define CRAZYFLIE_MESSAGE_PLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <crazyflie/Command.h>

namespace crazyflie
{
template <class ContainerAllocator>
struct Plan_
{
  typedef Plan_<ContainerAllocator> Type;

  Plan_()
    : time_interval_list()
    , command_list()  {
    }
  Plan_(const ContainerAllocator& _alloc)
    : time_interval_list(_alloc)
    , command_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _time_interval_list_type;
  _time_interval_list_type time_interval_list;

   typedef std::vector< ::crazyflie::Command_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::crazyflie::Command_<ContainerAllocator> >> _command_list_type;
  _command_list_type command_list;





  typedef boost::shared_ptr< ::crazyflie::Plan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crazyflie::Plan_<ContainerAllocator> const> ConstPtr;

}; // struct Plan_

typedef ::crazyflie::Plan_<std::allocator<void> > Plan;

typedef boost::shared_ptr< ::crazyflie::Plan > PlanPtr;
typedef boost::shared_ptr< ::crazyflie::Plan const> PlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crazyflie::Plan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crazyflie::Plan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::crazyflie::Plan_<ContainerAllocator1> & lhs, const ::crazyflie::Plan_<ContainerAllocator2> & rhs)
{
  return lhs.time_interval_list == rhs.time_interval_list &&
    lhs.command_list == rhs.command_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::crazyflie::Plan_<ContainerAllocator1> & lhs, const ::crazyflie::Plan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace crazyflie

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::crazyflie::Plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crazyflie::Plan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crazyflie::Plan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crazyflie::Plan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crazyflie::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "854ef745f169476b519c78ce5b33349d";
  }

  static const char* value(const ::crazyflie::Plan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x854ef745f169476bULL;
  static const uint64_t static_value2 = 0x519c78ce5b33349dULL;
};

template<class ContainerAllocator>
struct DataType< ::crazyflie::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crazyflie/Plan";
  }

  static const char* value(const ::crazyflie::Plan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crazyflie::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] time_interval_list\n"
"crazyflie/Command[] command_list\n"
"================================================================================\n"
"MSG: crazyflie/Command\n"
"float64 accel\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::crazyflie::Plan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crazyflie::Plan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_interval_list);
      stream.next(m.command_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Plan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crazyflie::Plan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crazyflie::Plan_<ContainerAllocator>& v)
  {
    s << indent << "time_interval_list[]" << std::endl;
    for (size_t i = 0; i < v.time_interval_list.size(); ++i)
    {
      s << indent << "  time_interval_list[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.time_interval_list[i]);
    }
    s << indent << "command_list[]" << std::endl;
    for (size_t i = 0; i < v.command_list.size(); ++i)
    {
      s << indent << "  command_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::crazyflie::Command_<ContainerAllocator> >::stream(s, indent + "    ", v.command_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CRAZYFLIE_MESSAGE_PLAN_H
