// Generated by gencpp from file pilot/Command.msg
// DO NOT EDIT!


#ifndef PILOT_MESSAGE_COMMAND_H
#define PILOT_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pilot
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : height(0.0)
    , accel(0.0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : height(0.0)
    , accel(0.0)  {
  (void)_alloc;
    }



   typedef double _height_type;
  _height_type height;

   typedef double _accel_type;
  _accel_type accel;





  typedef boost::shared_ptr< ::pilot::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pilot::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::pilot::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::pilot::Command > CommandPtr;
typedef boost::shared_ptr< ::pilot::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pilot::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pilot::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pilot::Command_<ContainerAllocator1> & lhs, const ::pilot::Command_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height &&
    lhs.accel == rhs.accel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pilot::Command_<ContainerAllocator1> & lhs, const ::pilot::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pilot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pilot::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pilot::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pilot::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pilot::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pilot::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pilot::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pilot::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "63158adff50f896215247bc385d77c11";
  }

  static const char* value(const ::pilot::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x63158adff50f8962ULL;
  static const uint64_t static_value2 = 0x15247bc385d77c11ULL;
};

template<class ContainerAllocator>
struct DataType< ::pilot::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pilot/Command";
  }

  static const char* value(const ::pilot::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pilot::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 height\n"
"float64 accel\n"
;
  }

  static const char* value(const ::pilot::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pilot::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.accel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pilot::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pilot::Command_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "accel: ";
    Printer<double>::stream(s, indent + "  ", v.accel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PILOT_MESSAGE_COMMAND_H
