// Generated by gencpp from file pilot/Log.msg
// DO NOT EDIT!


#ifndef PILOT_MESSAGE_LOG_H
#define PILOT_MESSAGE_LOG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pilot/Measurement.h>
#include <pilot/Command.h>
#include <pilot/MotorInput.h>

namespace pilot
{
template <class ContainerAllocator>
struct Log_
{
  typedef Log_<ContainerAllocator> Type;

  Log_()
    : stamp()
    , measurement()
    , command()
    , motor_input()  {
    }
  Log_(const ContainerAllocator& _alloc)
    : stamp()
    , measurement(_alloc)
    , command(_alloc)
    , motor_input(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef  ::pilot::Measurement_<ContainerAllocator>  _measurement_type;
  _measurement_type measurement;

   typedef  ::pilot::Command_<ContainerAllocator>  _command_type;
  _command_type command;

   typedef  ::pilot::MotorInput_<ContainerAllocator>  _motor_input_type;
  _motor_input_type motor_input;





  typedef boost::shared_ptr< ::pilot::Log_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pilot::Log_<ContainerAllocator> const> ConstPtr;

}; // struct Log_

typedef ::pilot::Log_<std::allocator<void> > Log;

typedef boost::shared_ptr< ::pilot::Log > LogPtr;
typedef boost::shared_ptr< ::pilot::Log const> LogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pilot::Log_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pilot::Log_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pilot::Log_<ContainerAllocator1> & lhs, const ::pilot::Log_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.measurement == rhs.measurement &&
    lhs.command == rhs.command &&
    lhs.motor_input == rhs.motor_input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pilot::Log_<ContainerAllocator1> & lhs, const ::pilot::Log_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pilot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pilot::Log_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pilot::Log_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pilot::Log_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pilot::Log_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pilot::Log_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pilot::Log_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pilot::Log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "27676e9e67f4024a10a6d61938d7a2ac";
  }

  static const char* value(const ::pilot::Log_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x27676e9e67f4024aULL;
  static const uint64_t static_value2 = 0x10a6d61938d7a2acULL;
};

template<class ContainerAllocator>
struct DataType< ::pilot::Log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pilot/Log";
  }

  static const char* value(const ::pilot::Log_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pilot::Log_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"pilot/Measurement measurement\n"
"pilot/Command command\n"
"pilot/MotorInput motor_input\n"
"================================================================================\n"
"MSG: pilot/Measurement\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"================================================================================\n"
"MSG: pilot/Command\n"
"float64 height\n"
"float64 accel\n"
"================================================================================\n"
"MSG: pilot/MotorInput\n"
"float64 m1_motor\n"
"float64 m2_motor\n"
"float64 m3_motor\n"
"float64 m4_motor\n"
;
  }

  static const char* value(const ::pilot::Log_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pilot::Log_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.measurement);
      stream.next(m.command);
      stream.next(m.motor_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Log_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pilot::Log_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pilot::Log_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "measurement: ";
    s << std::endl;
    Printer< ::pilot::Measurement_<ContainerAllocator> >::stream(s, indent + "  ", v.measurement);
    s << indent << "command: ";
    s << std::endl;
    Printer< ::pilot::Command_<ContainerAllocator> >::stream(s, indent + "  ", v.command);
    s << indent << "motor_input: ";
    s << std::endl;
    Printer< ::pilot::MotorInput_<ContainerAllocator> >::stream(s, indent + "  ", v.motor_input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PILOT_MESSAGE_LOG_H
