// Generated by gencpp from file pilot/Plan.msg
// DO NOT EDIT!


#ifndef PILOT_MESSAGE_PLAN_H
#define PILOT_MESSAGE_PLAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <pilot/Command.h>

namespace pilot
{
template <class ContainerAllocator>
struct Plan_
{
  typedef Plan_<ContainerAllocator> Type;

  Plan_()
    : interval_list()
    , command_list()  {
    }
  Plan_(const ContainerAllocator& _alloc)
    : interval_list(_alloc)
    , command_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _interval_list_type;
  _interval_list_type interval_list;

   typedef std::vector< ::pilot::Command_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::pilot::Command_<ContainerAllocator> >> _command_list_type;
  _command_list_type command_list;





  typedef boost::shared_ptr< ::pilot::Plan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pilot::Plan_<ContainerAllocator> const> ConstPtr;

}; // struct Plan_

typedef ::pilot::Plan_<std::allocator<void> > Plan;

typedef boost::shared_ptr< ::pilot::Plan > PlanPtr;
typedef boost::shared_ptr< ::pilot::Plan const> PlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pilot::Plan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pilot::Plan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pilot::Plan_<ContainerAllocator1> & lhs, const ::pilot::Plan_<ContainerAllocator2> & rhs)
{
  return lhs.interval_list == rhs.interval_list &&
    lhs.command_list == rhs.command_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pilot::Plan_<ContainerAllocator1> & lhs, const ::pilot::Plan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pilot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pilot::Plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pilot::Plan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pilot::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pilot::Plan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pilot::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pilot::Plan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pilot::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "84241112053e41dc4c45b618502e3991";
  }

  static const char* value(const ::pilot::Plan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x84241112053e41dcULL;
  static const uint64_t static_value2 = 0x4c45b618502e3991ULL;
};

template<class ContainerAllocator>
struct DataType< ::pilot::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pilot/Plan";
  }

  static const char* value(const ::pilot::Plan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pilot::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] interval_list\n"
"pilot/Command[] command_list\n"
"================================================================================\n"
"MSG: pilot/Command\n"
"float64 height\n"
"float64 accel\n"
;
  }

  static const char* value(const ::pilot::Plan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pilot::Plan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.interval_list);
      stream.next(m.command_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Plan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pilot::Plan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pilot::Plan_<ContainerAllocator>& v)
  {
    s << indent << "interval_list[]" << std::endl;
    for (size_t i = 0; i < v.interval_list.size(); ++i)
    {
      s << indent << "  interval_list[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.interval_list[i]);
    }
    s << indent << "command_list[]" << std::endl;
    for (size_t i = 0; i < v.command_list.size(); ++i)
    {
      s << indent << "  command_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::pilot::Command_<ContainerAllocator> >::stream(s, indent + "    ", v.command_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PILOT_MESSAGE_PLAN_H
