(cl:defpackage simulator-msg
  (:use )
  (:export
   "<COMMAND>"
   "COMMAND"
   "<LOG>"
   "LOG"
   "<MEASUREMENT>"
   "MEASUREMENT"
   "<MOTORINPUT>"
   "MOTORINPUT"
   "<PLANACTION>"
   "PLANACTION"
   "<PLANACTIONFEEDBACK>"
   "PLANACTIONFEEDBACK"
   "<PLANACTIONGOAL>"
   "PLANACTIONGOAL"
   "<PLANACTIONRESULT>"
   "PLANACTIONRESULT"
   "<PLANFEEDBACK>"
   "PLANFEEDBACK"
   "<PLANGOAL>"
   "PLANGOAL"
   "<PLANRESULT>"
   "PLANRESULT"
  ))

