; Auto-generated. Do not edit!


(cl:in-package pilot-msg)


;//! \htmlinclude SimulateGoal.msg.html

(cl:defclass <SimulateGoal> (roslisp-msg-protocol:ros-message)
  ((simulation_parameters
    :reader simulation_parameters
    :initarg :simulation_parameters
    :type pilot-msg:SimulationParameters
    :initform (cl:make-instance 'pilot-msg:SimulationParameters)))
)

(cl:defclass SimulateGoal (<SimulateGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SimulateGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SimulateGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pilot-msg:<SimulateGoal> is deprecated: use pilot-msg:SimulateGoal instead.")))

(cl:ensure-generic-function 'simulation_parameters-val :lambda-list '(m))
(cl:defmethod simulation_parameters-val ((m <SimulateGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pilot-msg:simulation_parameters-val is deprecated.  Use pilot-msg:simulation_parameters instead.")
  (simulation_parameters m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SimulateGoal>) ostream)
  "Serializes a message object of type '<SimulateGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'simulation_parameters) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SimulateGoal>) istream)
  "Deserializes a message object of type '<SimulateGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'simulation_parameters) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SimulateGoal>)))
  "Returns string type for a message object of type '<SimulateGoal>"
  "pilot/SimulateGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SimulateGoal)))
  "Returns string type for a message object of type 'SimulateGoal"
  "pilot/SimulateGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SimulateGoal>)))
  "Returns md5sum for a message object of type '<SimulateGoal>"
  "21babf6309a27d9c02ef58309c28fe13")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SimulateGoal)))
  "Returns md5sum for a message object of type 'SimulateGoal"
  "21babf6309a27d9c02ef58309c28fe13")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SimulateGoal>)))
  "Returns full string definition for message of type '<SimulateGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%pilot/SimulationParameters simulation_parameters~%~%================================================================================~%MSG: pilot/SimulationParameters~%string pilot_name~%string crazyflie_name~%int32 iteration_number~%time init_time~%pilot/Plan plan~%pilot/Box fly_box~%float64 fly_time~%================================================================================~%MSG: pilot/Plan~%float64[] interval_list~%pilot/Command[] command_list~%================================================================================~%MSG: pilot/Command~%float64 height~%float64 accel~%================================================================================~%MSG: pilot/Box~%float64 x_min~%float64 x_max~%float64 y_min~%float64 y_max~%float64 z_min~%float64 z_max~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SimulateGoal)))
  "Returns full string definition for message of type 'SimulateGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%pilot/SimulationParameters simulation_parameters~%~%================================================================================~%MSG: pilot/SimulationParameters~%string pilot_name~%string crazyflie_name~%int32 iteration_number~%time init_time~%pilot/Plan plan~%pilot/Box fly_box~%float64 fly_time~%================================================================================~%MSG: pilot/Plan~%float64[] interval_list~%pilot/Command[] command_list~%================================================================================~%MSG: pilot/Command~%float64 height~%float64 accel~%================================================================================~%MSG: pilot/Box~%float64 x_min~%float64 x_max~%float64 y_min~%float64 y_max~%float64 z_min~%float64 z_max~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SimulateGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'simulation_parameters))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SimulateGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SimulateGoal
    (cl:cons ':simulation_parameters (simulation_parameters msg))
))
