; Auto-generated. Do not edit!


(cl:in-package pilot-msg)


;//! \htmlinclude SimulateResult.msg.html

(cl:defclass <SimulateResult> (roslisp-msg-protocol:ros-message)
  ((simulation_results
    :reader simulation_results
    :initarg :simulation_results
    :type pilot-msg:SimulationResults
    :initform (cl:make-instance 'pilot-msg:SimulationResults)))
)

(cl:defclass SimulateResult (<SimulateResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SimulateResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SimulateResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pilot-msg:<SimulateResult> is deprecated: use pilot-msg:SimulateResult instead.")))

(cl:ensure-generic-function 'simulation_results-val :lambda-list '(m))
(cl:defmethod simulation_results-val ((m <SimulateResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pilot-msg:simulation_results-val is deprecated.  Use pilot-msg:simulation_results instead.")
  (simulation_results m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SimulateResult>) ostream)
  "Serializes a message object of type '<SimulateResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'simulation_results) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SimulateResult>) istream)
  "Deserializes a message object of type '<SimulateResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'simulation_results) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SimulateResult>)))
  "Returns string type for a message object of type '<SimulateResult>"
  "pilot/SimulateResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SimulateResult)))
  "Returns string type for a message object of type 'SimulateResult"
  "pilot/SimulateResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SimulateResult>)))
  "Returns md5sum for a message object of type '<SimulateResult>"
  "dc843a7027a129d61200f8f4bdae5d5d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SimulateResult)))
  "Returns md5sum for a message object of type 'SimulateResult"
  "dc843a7027a129d61200f8f4bdae5d5d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SimulateResult>)))
  "Returns full string definition for message of type '<SimulateResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%pilot/SimulationResults simulation_results~%~%================================================================================~%MSG: pilot/SimulationResults~%bool has_survived~%float64 survival_time~%float64 fitness~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SimulateResult)))
  "Returns full string definition for message of type 'SimulateResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%pilot/SimulationResults simulation_results~%~%================================================================================~%MSG: pilot/SimulationResults~%bool has_survived~%float64 survival_time~%float64 fitness~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SimulateResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'simulation_results))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SimulateResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SimulateResult
    (cl:cons ':simulation_results (simulation_results msg))
))
