; Auto-generated. Do not edit!


(cl:in-package pilot-msg)


;//! \htmlinclude SimulateFeedback.msg.html

(cl:defclass <SimulateFeedback> (roslisp-msg-protocol:ros-message)
  ((progress_percentage
    :reader progress_percentage
    :initarg :progress_percentage
    :type cl:fixnum
    :initform 0))
)

(cl:defclass SimulateFeedback (<SimulateFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SimulateFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SimulateFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name pilot-msg:<SimulateFeedback> is deprecated: use pilot-msg:SimulateFeedback instead.")))

(cl:ensure-generic-function 'progress_percentage-val :lambda-list '(m))
(cl:defmethod progress_percentage-val ((m <SimulateFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader pilot-msg:progress_percentage-val is deprecated.  Use pilot-msg:progress_percentage instead.")
  (progress_percentage m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SimulateFeedback>) ostream)
  "Serializes a message object of type '<SimulateFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'progress_percentage)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SimulateFeedback>) istream)
  "Deserializes a message object of type '<SimulateFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'progress_percentage)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SimulateFeedback>)))
  "Returns string type for a message object of type '<SimulateFeedback>"
  "pilot/SimulateFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SimulateFeedback)))
  "Returns string type for a message object of type 'SimulateFeedback"
  "pilot/SimulateFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SimulateFeedback>)))
  "Returns md5sum for a message object of type '<SimulateFeedback>"
  "107e41710fed83193baa98558e7f27ff")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SimulateFeedback)))
  "Returns md5sum for a message object of type 'SimulateFeedback"
  "107e41710fed83193baa98558e7f27ff")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SimulateFeedback>)))
  "Returns full string definition for message of type '<SimulateFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 progress_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SimulateFeedback)))
  "Returns full string definition for message of type 'SimulateFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%uint8 progress_percentage~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SimulateFeedback>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SimulateFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SimulateFeedback
    (cl:cons ':progress_percentage (progress_percentage msg))
))
