// Generated by gencpp from file orchestrator/EpochParameters.msg
// DO NOT EDIT!


#ifndef ORCHESTRATOR_MESSAGE_EPOCHPARAMETERS_H
#define ORCHESTRATOR_MESSAGE_EPOCHPARAMETERS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace orchestrator
{
template <class ContainerAllocator>
struct EpochParameters_
{
  typedef EpochParameters_<ContainerAllocator> Type;

  EpochParameters_()
    {
    }
  EpochParameters_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::orchestrator::EpochParameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::orchestrator::EpochParameters_<ContainerAllocator> const> ConstPtr;

}; // struct EpochParameters_

typedef ::orchestrator::EpochParameters_<std::allocator<void> > EpochParameters;

typedef boost::shared_ptr< ::orchestrator::EpochParameters > EpochParametersPtr;
typedef boost::shared_ptr< ::orchestrator::EpochParameters const> EpochParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::orchestrator::EpochParameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::orchestrator::EpochParameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace orchestrator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::orchestrator::EpochParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::orchestrator::EpochParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orchestrator::EpochParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::orchestrator::EpochParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orchestrator::EpochParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::orchestrator::EpochParameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::orchestrator::EpochParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::orchestrator::EpochParameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::orchestrator::EpochParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "orchestrator/EpochParameters";
  }

  static const char* value(const ::orchestrator::EpochParameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::orchestrator::EpochParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::orchestrator::EpochParameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::orchestrator::EpochParameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EpochParameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::orchestrator::EpochParameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::orchestrator::EpochParameters_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ORCHESTRATOR_MESSAGE_EPOCHPARAMETERS_H
