// Generated by gencpp from file simulator/Command.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_COMMAND_H
#define SIMULATOR_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct Command_
{
  typedef Command_<ContainerAllocator> Type;

  Command_()
    : accel(0.0)
    , dd_roll(0.0)  {
    }
  Command_(const ContainerAllocator& _alloc)
    : accel(0.0)
    , dd_roll(0.0)  {
  (void)_alloc;
    }



   typedef double _accel_type;
  _accel_type accel;

   typedef double _dd_roll_type;
  _dd_roll_type dd_roll;





  typedef boost::shared_ptr< ::simulator::Command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::Command_<ContainerAllocator> const> ConstPtr;

}; // struct Command_

typedef ::simulator::Command_<std::allocator<void> > Command;

typedef boost::shared_ptr< ::simulator::Command > CommandPtr;
typedef boost::shared_ptr< ::simulator::Command const> CommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::Command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::Command_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::Command_<ContainerAllocator1> & lhs, const ::simulator::Command_<ContainerAllocator2> & rhs)
{
  return lhs.accel == rhs.accel &&
    lhs.dd_roll == rhs.dd_roll;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::Command_<ContainerAllocator1> & lhs, const ::simulator::Command_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::Command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::Command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::Command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::Command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f48091e0b3a7fa4bae99174051aca91d";
  }

  static const char* value(const ::simulator::Command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf48091e0b3a7fa4bULL;
  static const uint64_t static_value2 = 0xae99174051aca91dULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/Command";
  }

  static const char* value(const ::simulator::Command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::Command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 accel\n"
"float64 dd_roll\n"
;
  }

  static const char* value(const ::simulator::Command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::Command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accel);
      stream.next(m.dd_roll);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::Command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::Command_<ContainerAllocator>& v)
  {
    s << indent << "accel: ";
    Printer<double>::stream(s, indent + "  ", v.accel);
    s << indent << "dd_roll: ";
    Printer<double>::stream(s, indent + "  ", v.dd_roll);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_COMMAND_H
