// Generated by gencpp from file simulator/PlanGoal.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_PLANGOAL_H
#define SIMULATOR_MESSAGE_PLANGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <simulator/Command.h>

namespace simulator
{
template <class ContainerAllocator>
struct PlanGoal_
{
  typedef PlanGoal_<ContainerAllocator> Type;

  PlanGoal_()
    : interval_list()
    , command_list()  {
    }
  PlanGoal_(const ContainerAllocator& _alloc)
    : interval_list(_alloc)
    , command_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _interval_list_type;
  _interval_list_type interval_list;

   typedef std::vector< ::simulator::Command_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::simulator::Command_<ContainerAllocator> >> _command_list_type;
  _command_list_type command_list;





  typedef boost::shared_ptr< ::simulator::PlanGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::PlanGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PlanGoal_

typedef ::simulator::PlanGoal_<std::allocator<void> > PlanGoal;

typedef boost::shared_ptr< ::simulator::PlanGoal > PlanGoalPtr;
typedef boost::shared_ptr< ::simulator::PlanGoal const> PlanGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::PlanGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::PlanGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simulator::PlanGoal_<ContainerAllocator1> & lhs, const ::simulator::PlanGoal_<ContainerAllocator2> & rhs)
{
  return lhs.interval_list == rhs.interval_list &&
    lhs.command_list == rhs.command_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simulator::PlanGoal_<ContainerAllocator1> & lhs, const ::simulator::PlanGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::simulator::PlanGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::PlanGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::PlanGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::PlanGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::PlanGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::PlanGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::PlanGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f4531cf2ab9293bc63bad7d599cfe6cf";
  }

  static const char* value(const ::simulator::PlanGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf4531cf2ab9293bcULL;
  static const uint64_t static_value2 = 0x63bad7d599cfe6cfULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::PlanGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/PlanGoal";
  }

  static const char* value(const ::simulator::PlanGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::PlanGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float64[] interval_list\n"
"simulator/Command[] command_list\n"
"\n"
"================================================================================\n"
"MSG: simulator/Command\n"
"float64 accel\n"
"float64 dd_roll\n"
;
  }

  static const char* value(const ::simulator::PlanGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::PlanGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.interval_list);
      stream.next(m.command_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::PlanGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::PlanGoal_<ContainerAllocator>& v)
  {
    s << indent << "interval_list[]" << std::endl;
    for (size_t i = 0; i < v.interval_list.size(); ++i)
    {
      s << indent << "  interval_list[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.interval_list[i]);
    }
    s << indent << "command_list[]" << std::endl;
    for (size_t i = 0; i < v.command_list.size(); ++i)
    {
      s << indent << "  command_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::simulator::Command_<ContainerAllocator> >::stream(s, indent + "    ", v.command_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_PLANGOAL_H
