// Auto-generated. Do not edit!

// (in-package pilot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let SimulationResults = require('./SimulationResults.js');

//-----------------------------------------------------------

class SimulateResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.simulation_results = null;
    }
    else {
      if (initObj.hasOwnProperty('simulation_results')) {
        this.simulation_results = initObj.simulation_results
      }
      else {
        this.simulation_results = new SimulationResults();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SimulateResult
    // Serialize message field [simulation_results]
    bufferOffset = SimulationResults.serialize(obj.simulation_results, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SimulateResult
    let len;
    let data = new SimulateResult(null);
    // Deserialize message field [simulation_results]
    data.simulation_results = SimulationResults.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 17;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pilot/SimulateResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dc843a7027a129d61200f8f4bdae5d5d';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    pilot/SimulationResults simulation_results
    
    ================================================================================
    MSG: pilot/SimulationResults
    bool has_survived
    float64 survival_time
    float64 fitness
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SimulateResult(null);
    if (msg.simulation_results !== undefined) {
      resolved.simulation_results = SimulationResults.Resolve(msg.simulation_results)
    }
    else {
      resolved.simulation_results = new SimulationResults()
    }

    return resolved;
    }
};

module.exports = SimulateResult;
