// Auto-generated. Do not edit!

// (in-package pilot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let SimulationParameters = require('./SimulationParameters.js');

//-----------------------------------------------------------

class SimulateGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.simulation_parameters = null;
    }
    else {
      if (initObj.hasOwnProperty('simulation_parameters')) {
        this.simulation_parameters = initObj.simulation_parameters
      }
      else {
        this.simulation_parameters = new SimulationParameters();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SimulateGoal
    // Serialize message field [simulation_parameters]
    bufferOffset = SimulationParameters.serialize(obj.simulation_parameters, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SimulateGoal
    let len;
    let data = new SimulateGoal(null);
    // Deserialize message field [simulation_parameters]
    data.simulation_parameters = SimulationParameters.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += SimulationParameters.getMessageSize(object.simulation_parameters);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pilot/SimulateGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '21babf6309a27d9c02ef58309c28fe13';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    pilot/SimulationParameters simulation_parameters
    
    ================================================================================
    MSG: pilot/SimulationParameters
    string pilot_name
    string crazyflie_name
    int32 iteration_number
    time init_time
    pilot/Plan plan
    pilot/Box fly_box
    float64 fly_time
    ================================================================================
    MSG: pilot/Plan
    float64[] interval_list
    pilot/Command[] command_list
    ================================================================================
    MSG: pilot/Command
    float64 height
    float64 accel
    ================================================================================
    MSG: pilot/Box
    float64 x_min
    float64 x_max
    float64 y_min
    float64 y_max
    float64 z_min
    float64 z_max
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SimulateGoal(null);
    if (msg.simulation_parameters !== undefined) {
      resolved.simulation_parameters = SimulationParameters.Resolve(msg.simulation_parameters)
    }
    else {
      resolved.simulation_parameters = new SimulationParameters()
    }

    return resolved;
    }
};

module.exports = SimulateGoal;
