// Auto-generated. Do not edit!

// (in-package pilot.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SimulateFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.progress_percentage = null;
    }
    else {
      if (initObj.hasOwnProperty('progress_percentage')) {
        this.progress_percentage = initObj.progress_percentage
      }
      else {
        this.progress_percentage = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SimulateFeedback
    // Serialize message field [progress_percentage]
    bufferOffset = _serializer.uint8(obj.progress_percentage, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SimulateFeedback
    let len;
    let data = new SimulateFeedback(null);
    // Deserialize message field [progress_percentage]
    data.progress_percentage = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'pilot/SimulateFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '107e41710fed83193baa98558e7f27ff';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    uint8 progress_percentage
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SimulateFeedback(null);
    if (msg.progress_percentage !== undefined) {
      resolved.progress_percentage = msg.progress_percentage;
    }
    else {
      resolved.progress_percentage = 0
    }

    return resolved;
    }
};

module.exports = SimulateFeedback;
