# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from pilot/SimulateActionGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import actionlib_msgs.msg
import genpy
import pilot.msg
import std_msgs.msg

class SimulateActionGoal(genpy.Message):
  _md5sum = "bd5ff790fb2f85bb400ee52043a2523d"
  _type = "pilot/SimulateActionGoal"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======

Header header
actionlib_msgs/GoalID goal_id
SimulateGoal goal

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: actionlib_msgs/GoalID
# The stamp should store the time at which this goal was requested.
# It is used by an action server when it tries to preempt all
# goals that were requested before a certain time
time stamp

# The id provides a way to associate feedback and
# result message with specific goal requests. The id
# specified must be unique.
string id


================================================================================
MSG: pilot/SimulateGoal
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
pilot/SimulationParameters simulation_parameters

================================================================================
MSG: pilot/SimulationParameters
string pilot_name
string crazyflie_name
int32 iteration_number
time init_time
pilot/Plan plan
pilot/Box fly_box
float64 fly_time
================================================================================
MSG: pilot/Plan
float64[] interval_list
pilot/Command[] command_list
================================================================================
MSG: pilot/Command
float64 height
float64 accel
================================================================================
MSG: pilot/Box
float64 x_min
float64 x_max
float64 y_min
float64 y_max
float64 z_min
float64 z_max"""
  __slots__ = ['header','goal_id','goal']
  _slot_types = ['std_msgs/Header','actionlib_msgs/GoalID','pilot/SimulateGoal']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,goal_id,goal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SimulateActionGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = pilot.msg.SimulateGoal()
    else:
      self.header = std_msgs.msg.Header()
      self.goal_id = actionlib_msgs.msg.GoalID()
      self.goal = pilot.msg.SimulateGoal()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs))
      _x = self.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.goal.simulation_parameters.pilot_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.goal.simulation_parameters.crazyflie_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i2I().pack(_x.goal.simulation_parameters.iteration_number, _x.goal.simulation_parameters.init_time.secs, _x.goal.simulation_parameters.init_time.nsecs))
      length = len(self.goal.simulation_parameters.plan.interval_list)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.goal.simulation_parameters.plan.interval_list))
      length = len(self.goal.simulation_parameters.plan.command_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.simulation_parameters.plan.command_list:
        _x = val1
        buff.write(_get_struct_2d().pack(_x.height, _x.accel))
      _x = self
      buff.write(_get_struct_7d().pack(_x.goal.simulation_parameters.fly_box.x_min, _x.goal.simulation_parameters.fly_box.x_max, _x.goal.simulation_parameters.fly_box.y_min, _x.goal.simulation_parameters.fly_box.y_max, _x.goal.simulation_parameters.fly_box.z_min, _x.goal.simulation_parameters.fly_box.z_max, _x.goal.simulation_parameters.fly_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = pilot.msg.SimulateGoal()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_id.id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal.simulation_parameters.pilot_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal.simulation_parameters.pilot_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal.simulation_parameters.crazyflie_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal.simulation_parameters.crazyflie_name = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.goal.simulation_parameters.iteration_number, _x.goal.simulation_parameters.init_time.secs, _x.goal.simulation_parameters.init_time.nsecs,) = _get_struct_i2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal.simulation_parameters.plan.interval_list = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.simulation_parameters.plan.command_list = []
      for i in range(0, length):
        val1 = pilot.msg.Command()
        _x = val1
        start = end
        end += 16
        (_x.height, _x.accel,) = _get_struct_2d().unpack(str[start:end])
        self.goal.simulation_parameters.plan.command_list.append(val1)
      _x = self
      start = end
      end += 56
      (_x.goal.simulation_parameters.fly_box.x_min, _x.goal.simulation_parameters.fly_box.x_max, _x.goal.simulation_parameters.fly_box.y_min, _x.goal.simulation_parameters.fly_box.y_max, _x.goal.simulation_parameters.fly_box.z_min, _x.goal.simulation_parameters.fly_box.z_max, _x.goal.simulation_parameters.fly_time,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs))
      _x = self.goal_id.id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.goal.simulation_parameters.pilot_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.goal.simulation_parameters.crazyflie_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i2I().pack(_x.goal.simulation_parameters.iteration_number, _x.goal.simulation_parameters.init_time.secs, _x.goal.simulation_parameters.init_time.nsecs))
      length = len(self.goal.simulation_parameters.plan.interval_list)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.goal.simulation_parameters.plan.interval_list.tostring())
      length = len(self.goal.simulation_parameters.plan.command_list)
      buff.write(_struct_I.pack(length))
      for val1 in self.goal.simulation_parameters.plan.command_list:
        _x = val1
        buff.write(_get_struct_2d().pack(_x.height, _x.accel))
      _x = self
      buff.write(_get_struct_7d().pack(_x.goal.simulation_parameters.fly_box.x_min, _x.goal.simulation_parameters.fly_box.x_max, _x.goal.simulation_parameters.fly_box.y_min, _x.goal.simulation_parameters.fly_box.y_max, _x.goal.simulation_parameters.fly_box.z_min, _x.goal.simulation_parameters.fly_box.z_max, _x.goal.simulation_parameters.fly_time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_id is None:
        self.goal_id = actionlib_msgs.msg.GoalID()
      if self.goal is None:
        self.goal = pilot.msg.SimulateGoal()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.goal_id.stamp.secs, _x.goal_id.stamp.nsecs,) = _get_struct_2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_id.id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal_id.id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal.simulation_parameters.pilot_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal.simulation_parameters.pilot_name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal.simulation_parameters.crazyflie_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.goal.simulation_parameters.crazyflie_name = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.goal.simulation_parameters.iteration_number, _x.goal.simulation_parameters.init_time.secs, _x.goal.simulation_parameters.init_time.nsecs,) = _get_struct_i2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.goal.simulation_parameters.plan.interval_list = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.goal.simulation_parameters.plan.command_list = []
      for i in range(0, length):
        val1 = pilot.msg.Command()
        _x = val1
        start = end
        end += 16
        (_x.height, _x.accel,) = _get_struct_2d().unpack(str[start:end])
        self.goal.simulation_parameters.plan.command_list.append(val1)
      _x = self
      start = end
      end += 56
      (_x.goal.simulation_parameters.fly_box.x_min, _x.goal.simulation_parameters.fly_box.x_max, _x.goal.simulation_parameters.fly_box.y_min, _x.goal.simulation_parameters.fly_box.y_max, _x.goal.simulation_parameters.fly_box.z_min, _x.goal.simulation_parameters.fly_box.z_max, _x.goal.simulation_parameters.fly_time,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
_struct_i2I = None
def _get_struct_i2I():
    global _struct_i2I
    if _struct_i2I is None:
        _struct_i2I = struct.Struct("<i2I")
    return _struct_i2I
